### ISSUE TITLE
automatically collect proxies

### ISSUE THREAD

**Issue by Almenon** [watzon/wsl-proxy#11]
It wouldn't be too hard to write something to go through the results of `wsl ls /usr/bin` and format them as individual batch files.  If I have time I might try this out, otherwise you're welcome to it ;)

**Comment by watzon** [comment]
It would be awesome if you find the time. I never expected this project to get so popular, but I love contributions

**Comment by flowstatedev** [comment]
Awesome project! I created a pull request to try to address this issue:
https://github.com/watzon/wsl-proxy/pull/14

**Comment by watzon** [comment]
Solved with #14
