### ISSUE TITLE
Windows paths?

### ISSUE THREAD

**Issue by gmask** [watzon/wsl-proxy#2]
Hey there, this is a cool project, however I'm not entirely sure about file path translation, currently I'm doing some dirty stuff to hand the correct paths over to the WSL side. For example, here's my `php-cs-fixer.bat` file:

**php-cs-fixer.bat:**
```
@echo off

SET "fix_file=%1"

for /f %%i in ('convert_path %fix_file%') do set file_path=%%i

bash.exe -c "~/.composer/vendor/bin/php-cs-fixer fix %file_path% --rules=@PSR2"

@echo on
```

And here's what I have to do to convert the paths from Sublime Text's `$file` and `$folder` parameters:

**convert_path.bat:**
```
@echo OFF

set "variable=%1"

set "drive=%variable:~0,1%"

set variable=%variable:~2%
set "variable=%variable:\=/%"

if %drive%==C set "drive=c"
if %drive%==D set "drive=d"
if %drive%==E set "drive=e"

set "variable=/mnt/%drive%%variable%"

echo "%variable%"

@echo ON
```

Which translates `C:\Path\to\file.php` to `/mnt/c/Path/to/file.php` but is extremely gross. Is there a better way to achieve this? Do I have to do this for each proxy?

The other issue is that I cannot just call any Composer packages directly from `bash.exe -c`, I get this error: `/bin/bash: phpcs: command not found`, however when I call `bash.exe -c "~/.composer/vendor/bin/phpcs %*"` instead it works. Is there any way to get this to work like the former with global Composer files?

**Comment by watzon** [comment]
I'll answer the last question first. It seems like your composer `bin` directory isn't in your PATH. Either that or it was added to your PATH using `.zshrc` or something else that's not `.bashrc`. Make sure it is on your path and accessible via `bash`.

As far as your main question I really don't know what to tell you. Maybe we can add certain "utility" files to a special folder and then call them like you did in `php-cs-fixer.bat`. You'd need to generalize `convert-path.bat` a little (i.e. don't hard code in drive letters, rather just take the first letter and lowercase it), but it would make a great start.

**Comment by gmask** [comment]
I've since gone back to native build tools since the interop between Windows and Bash isn't quite there yet.
